build:
# g++ main.cpp -o main -lglut -lGLU -lGL
# ./main
# g++ main3d.cpp -o main3d -lglut -lGLU -lGL
# ./main3d
# g++ GL3_polyhedron.cpp -o main3d -lglut -lGLU -lGL
# ./main3d

	g++ 3d_bezier_curves.cpp -o 3d_bezier_curves -lglut -lGLU -lGL -lglfw
	./3d_bezier_curves
