build:
# g++ main_via_func.cpp -o main_via_func -lglut -lGLU -lGL
# ./main_via_func

#	g++ main.cpp -o main -lglut -lGLU -lGL
#	./main

	g++ main3d.cpp -o main3d -lglut -lGLU -lGL
	./main3d

# g++ GL3_polyhedron.cpp -o main3d -lglut -lGLU -lGL
# ./main3d
